version: "3.4"

services:
# NODE JS CONTAINER
  # bun-app:
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:${PORT}
  #   environment:
  #     PORT: ${PORT}
  #     DATABASE_URL: ${DATABASE_URL}
  #     JWT_SECRET: ${JWT_SECRET}
  #   networks:
  #     - edevlop-network
# POSTGRESDB CONTAINER
  postgres:
    container_name: postgres
    env_file:
      - .env
    image: postgres
    restart: always
    ports: 
      - 5432:${POSTGRESQL_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - edevlop-network


# NETWORKS
networks:
  edevlop-network:
    driver: bridge

# VOLUMES
volumes:
  postgres_data:
